import Head from "next/head"
import { useDispatch, useSelector } from "react-redux"
import { decrement, increment, selectValue } from "../slices/CounterSlice"
import styles from "../styles/Home.module.css"

export default function Home() {
  const count = useSelector(selectValue)
  const dispatch = useDispatch()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>The value is {count}</h1>
        <button onClick={() => dispatch(increment())}>increment</button>
        <button onClick={() => dispatch(decrement())}>decrement</button>
      </main>
    </div>
  )
}
